# Site settings
title: Ayush Jain
description: Personal Website of Ayush Jain
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ayush Jain
user_description: Remember back in middle school we were taught system of equations, equalities and inequalities? It was so much fun, drawing shaded region in a two dimensional piece of paper. At that point I had no idea I could make a living out of it until I came across Operations Research. Now, I do similar things on a much larger scale, using sophisticated algorithms for real world problems. I work as an Optimization modeler in supply chain for a manufacturing company in Seattle, Washington.
user_title: Optimization Modeler
email: ayushj94@bu.edu
# twitter_username: lorem_ipsum
github_username:  ayushjain1594
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
