# Site settings
title: Ayush Jain
description: Personal Website of Ayush Jain
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ayush Jain
user_description: I am an Optimization Modeler with 2 years of experience developing solutions for optimization problems in supply chain.
user_title: Optimization Modeler
email: ayushj94@bu.edu
# twitter_username: lorem_ipsum
github_username:  ayushjain1594
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
